In [34]:
import pandas as pd
from pathlib import Path
import os

print("Directorio de trabajo actual:")
print(os.getcwd())

Directorio de trabajo actual:
C:\Reseñas_turisticas_CR\Rese-as-turisticas\notebooks

In [38]:
import pandas as pd
from pathlib import Path

ruta_final = proyecto / 'data' / 'raw' / 'final'
archivo = 'resenas_google_maps.csv'

df = pd.read_csv(ruta_final / archivo)

print("Dataset cargado")
print("Dimensiones:", df.shape)
print("Columnas:", df.columns.tolist())
df.head(3)

Dataset cargado
Dimensiones: (3400, 66)
Columnas: ['query', 'name', 'category', 'google_id', 'place_id', 'location_link', 'reviews_link', 'reviews_per_score', 'reviews', 'rating', 'review_id', 'review_pagination_id', 'author_link', 'author_title', 'author_id', 'author_image', 'author_reviews_count', 'author_ratings_count', 'review_text', 'review_img_urls', 'review_img_url', 'review_questions_Trip type', 'review_questions_Travel group', 'review_photo_ids', 'owner_answer', 'owner_answer_timestamp', 'owner_answer_timestamp_datetime_utc', 'review_link', 'review_rating', 'review_timestamp', 'review_datetime_utc', 'review_likes', 'reviews_id', 'review_questions_Rooms', 'review_questions_Service', 'review_questions_Location', 'review_questions_Nearby activities', 'review_questions_Safety', 'review_questions_Hotel highlights', 'review_questions_None', 'review_questions', 'review_questions_Walkability', 'review_questions_Food & drinks', 'review_questions_Noteworthy details', 'review_questions_Food', 'review_questions_Atmosphere', 'review_questions_Meal type', 'review_questions_Price per person', 'review_questions_Noise level', 'review_questions_Wait time', 'review_questions_Group size', 'review_questions_Seating type', 'review_questions_Reservation', 'review_questions_Vegetarian options', 'review_questions_Dietary restrictions', 'review_questions_Parking space', 'review_questions_Parking options', 'review_questions_Kid-friendliness', 'review_questions_Wheelchair accessibility', 'review_questions_Parking', 'review_questions_Order type', 'review_questions_Special events', 'review_questions_Recommended dishes', 'review_questions_Special offers', '-----', '-']

,query,name,category,google_id,place_id,location_link,reviews_link,reviews_per_score,reviews,rating,review_id,review_pagination_id,author_link,author_title,author_id,author_image,author_reviews_count,author_ratings_count,review_text,review_img_urls,review_img_url,review_questions_Trip type,review_questions_Travel group,review_photo_ids,owner_answer,owner_answer_timestamp,owner_answer_timestamp_datetime_utc,review_link,review_rating,review_timestamp,review_datetime_utc,review_likes,reviews_id,review_questions_Rooms,review_questions_Service,review_questions_Location,review_questions_Nearby activities,review_questions_Safety,review_questions_Hotel highlights,review_questions_None,review_questions,review_questions_Walkability,review_questions_Food & drinks,review_questions_Noteworthy details,review_questions_Food,review_questions_Atmosphere,review_questions_Meal type,review_questions_Price per person,review_questions_Noise level,review_questions_Wait time,review_questions_Group size,review_questions_Seating type,review_questions_Reservation,review_questions_Vegetarian options,review_questions_Dietary restrictions,review_questions_Parking space,review_questions_Parking options,review_questions_Kid-friendliness,review_questions_Wheelchair accessibility,review_questions_Parking,review_questions_Order type,review_questions_Special events,review_questions_Recommended dishes,review_questions_Special offers,-----,-
0,0x8fa00c07b7f23239:0x3e406fbb8226738e,Baldi Hot Springs Hotel Resort & Spa,Hotel,0x8fa00c07b7f23239:0x3e406fbb8226738e,ChIJOTLytwcMoI8RjnMmgrtvQD4,"https://www.google.com/maps/place/Baldi+Hot+Springs+Hotel+Resort+%26+Spa/@10.4831285,-84.68064629999999,14z/data=!4m8!1m2!2m1!1sBaldi+Hot+Springs+Hotel+Resort+%26+Spa!3m4!1s0x8fa00c07b7f23239:0x3e406fbb8226738e!8m2!3d10.4831285!4d-84.68064629999999",https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,NaN,8827,4.5,Ci9DQUlRQUNvZENodHljRjlvT21oc1dUWlVTbTF4TVVRM1JHUlZXV3h1WkhaSGVFRRAB,Ci8IARInCgoAP72GFgchYW__EhB_ZNPQXBdGr9i42hoAAAAAGgf_AmFgchYWGAAiAA:1,https://www.google.com/maps/contrib/112135482568653024758?hl=en,Chris Anderson,1.121355e+20,https://lh3.googleusercontent.com/a-/ALV-UjWl18blNCsmtCSoVO4LCGUEJu60wVvxRFpwpzdBjtgC5XVfw3nhyw=s120-c-rp-mo-ba5-br100,57.0,53.0,"We just did the hot springs and slides for the day. The water slides are crazy awesome, even the kids toilet bowl slide was more extreme than we get in the States. Laying in the top hot spring during a downpour was amazing.",NaN,NaN,Vacation,Friends,NaN,NaN,NaN,NaN,https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21oc1dUWlVTbTF4TVVRM1JHUlZXV3h1WkhaSGVFRRAB!2m1!1s0x0:0x3e406fbb8226738e!3m1!1s2@1:CAIQACodChtycF9oOmhsWTZUSm1xMUQ3RGRVWWxuZHZHeEE%7C%7C?hl=en,5.0,1780793338,06/07/2026 00:48:58,NaN,4485708079994139534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0x8fa00c07b7f23239:0x3e406fbb8226738e,Baldi Hot Springs Hotel Resort & Spa,Hotel,0x8fa00c07b7f23239:0x3e406fbb8226738e,ChIJOTLytwcMoI8RjnMmgrtvQD4,"https://www.google.com/maps/place/Baldi+Hot+Springs+Hotel+Resort+%26+Spa/@10.4831285,-84.68064629999999,14z/data=!4m8!1m2!2m1!1sBaldi+Hot+Springs+Hotel+Resort+%26+Spa!3m4!1s0x8fa00c07b7f23239:0x3e406fbb8226738e!8m2!3d10.4831285!4d-84.68064629999999",https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,NaN,8827,4.5,Ci9DQUlRQUNvZENodHljRjlvT21kWVRHNVhhVU5TWlRacmRuRkhUV3RVVjNsbWRHYxAB,Ci8IARInCgoAP72GFsRzzo__EhBhQGBqQSFsI2LridwAAAAAGgf_AmFsRzzoGAAiAA:2,https://www.google.com/maps/contrib/100918772214214654057?hl=en,Kimberly Sober,1.009188e+20,https://lh3.googleusercontent.com/a/ACg8ocJAmc_DKcz1Yyo-r_nI3tTdnfA3DQrnQCfs6UXXYLJGpSkZZA=s120-c-rp-mo-ba4-br100,71.0,0.0,"I read a lot of negative reviews a few days before we arrived, and I was outside the cancelation window, so we had to make the best of it.\r\nThis place is amazing! We stayed 3 nights 6/1-6/4. The resort is very well maintained and clean. The check in process was very easy. They accepted.credit card (did not require bank transfer) and allowed us to call our credit card and authorize international charges. They were patient and accommodating. Everyone we met was friendly and helpful. The rooms are huge and nice! They had robes, shaving kit, dental kit, sewing kit, lotion, shampoo, and conditioner. The room had coffee! Great patio area! We booked 2 and had connecting rooms.\r\nThe hot springs were not busy or over crowded. It rained every day, sometimes showers or torrential downpour. The breakfast was okay, not a huge selection but enough to satisfy everyone in our party. We got a couple burgers one night ($14.50 each) they were decent. The last night we got some dishes to take back to the room. (Fettuccine alfredo, nachos, Mediterranean salad). The salad with grilled chicken, candied nuts, fresh vegetables was delicious. My 7 year old barely let me get a bite.\r\nThere is a small market if you walk outside to the right, you can grab alcohol, snacks, candy etc. Soda Typical is also there we got chicken quesadillas ($8) and an amazing hamburger for $9.\r\nCheck out was simple, we called and asked to send the cart at 10:30 as we had transportation picking us up at 11. The front desk was friendly and told us to wait a few minutes while they checked the room. (We travel often and this is normal so we were prepared, I read they care about towels, robes, and umbrellas, so I had everything laying out in piles). It took 5 minutes max! They cut off the bands printed our bill and there were not any extra or hidden charges.\r\nThey do sell alcohol and it ranges from $11-20 a drink. You can put it on a card or pay cash. Expect normal American prices at the resort. The workers glady accept tips but the new credit card software does not allow you to tip (just as an fyi). The slides-watch people go down them and ask about their experience before allowing your children or self to try. There were 2 that I Did not allow my 7 year old on (the blue and yellow one near kids area and the middle one (serpentine) with the group of slides. All others they loved.\r\nOverall amazing experience.","https://lh3.googleusercontent.com/grass-cs/ANxoTn2fLwQOhgRGfOJbDYHaQk6VU45e4J9e645E1eAKJk776-HpYeMQ-wAAqUlN42iybuQ8Qq_J0n-5-Ao0rn6xfJnral-GzsW_-PC1VsP_WvN_xMT64b1b3FBzwcsbMrU2TW5zZ57XKxcAowI, https://lh3.googleusercontent.com/grass-cs/ANxoTn35PBECknCdno0Ez2dvsOQOjnEYsiJ4EDz4K8KOV0_nyxSbHlxueoqCLAdV280Gqlc2-XKb9vZEmfac-Zhb-5fyPlLGFIO1JMCfYHAucb4jIk-HBYjmFYbgQXz6s6eIs-LClFA6KZHwOLkF, https://lh3.googleusercontent.com/grass-cs/ANxoTn2pk4wNFBXbpAC9ncgrNGKtnWtR1j4Hc_a0zljpAJA4IdvHlQyDSsuqf1-9BMUSwDCn7EPZQUP6Tu_MfK11su4y8rmNxgAqVVlE2pDpGTETEG97zxpONR6jyGVy8JsMVrSZp3fZSu_Ir_ga, https://lh3.googleusercontent.com/grass-cs/ANxoTn3II_blzRc4Od8x-bNIXfgoupQx0JbJo7M2gumGJi_B2dWf56Rvy-Y0Pk6rvsZFaLa2oZWQpryzB9qJAjjr51T024klqaBtWPy_HR1ZOLdEYC1tXKEyUjMxsyyHhOiRc3xSkbngL57Al5A, https://lh3.googleusercontent.com/grass-cs/ANxoTn3xtEaMTkx2VZXRVxMiTFVC1xCLaK76q8k7b3u6JJK9PxDe7kz1DvN6c6X0YgvxSk7Uk_tZJnJ2zTT9bObCqzOGa32u2BjVkiCfr1av9wCS54tEDojPMjbUG_vALgr3pxWuFosnFbwO9IrP, https://lh3.googleusercontent.com/grass-cs/ANxoTn1QAUJ-jy1v7TBSPT46-D9Er-Emjti8HNNm5xUhK95MitvkMaEjHDG8HPMY-DT4wj_qR7ALr1rHvfVPjZZtM8XbAgyNTvauYiHQkO1ZHy7FAlERUQ-IO_voIQX45kPbuakvHUkSBdFWEALO",https://lh3.googleusercontent.com/grass-cs/ANxoTn2fLwQOhgRGfOJbDYHaQk6VU45e4J9e645E1eAKJk776-HpYeMQ-wAAqUlN42iybuQ8Qq_J0n-5-Ao0rn6xfJnral-GzsW_-PC1VsP_WvN_xMT64b1b3FBzwcsbMrU2TW5zZ57XKxcAowI=k-no,Vacation,Family,"CIABIhBHUI6AOckJpcISzcYNbUuz, CIABIhAcqZYYy7k4mLRvoN2_EVTj, CIABIhBLbHj_W5-4243AlE4FpQQ4, CIABIhDmXTx2_TzfiaU1uamzfenz, CIABIhClz9LNqrHgIL0e1rKf2L2l, CIABIhBwrHixlMP4W7Q0dLf7PndC",NaN,NaN,NaN,https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT21kWVRHNVhhVU5TWlRacmRuRkhUV3RVVjNsbWRHYxAB!2m1!1s0x0:0x3e406fbb8226738e!3m1!1s2@1:CAIQACodChtycF9oOmdYTG5XaUNSZTZrdnFHTWtUV3lmdGc%7C%7C?hl=en,5.0,1780594819,06/04/2026 17:40:19,NaN,4485708079994139534,NaN,5.0,5.0,NaN,NaN,"Luxury, Kid-friendly","Rooms, Nearby activities, Safety",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0x8fa00c07b7f23239:0x3e406fbb8226738e,Baldi Hot Springs Hotel Resort & Spa,Hotel,0x8fa00c07b7f23239:0x3e406fbb8226738e,ChIJOTLytwcMoI8RjnMmgrtvQD4,"https://www.google.com/maps/place/Baldi+Hot+Springs+Hotel+Resort+%26+Spa/@10.4831285,-84.68064629999999,14z/data=!4m8!1m2!2m1!1sBaldi+Hot+Springs+Hotel+Resort+%26+Spa!3m4!1s0x8fa00c07b7f23239:0x3e406fbb8226738e!8m2!3d10.4831285!4d-84.68064629999999",https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,NaN,8827,4.5,Ci9DQUlRQUNvZENodHljRjlvT25scllXTmZRa0ZtVEZSVlMyNXNRek5STW1GeWIxRRAB,Ci8IARInCgoAP72GFxn6Hx__EhCZgLWYAbcvxMaqsBkAAAAAGgf_AmFxn6HxGAAiAA:3,https://www.google.com/maps/contrib/112208520019130980479?hl=en,Richard Hayden,1.122085e+20,https://lh3.googleusercontent.com/a-/ALV-UjX_eIArYHIpduNgyFvtI7tCf08QuwGDEdl8dg9X4o68vdN1yRvw=s120-c-rp-mo-ba3-br100,75.0,102.0,This resort was amazing. We had two different rooms in different buildings. To check in was very easy. The hot springs were incredible and so many to try. The grounds were beyond lush. Great location near town. Very helpful and friendly staff. Luxury linens in the rooms including pooll towels. The breakfast buffet was included with our room and was delicious every morning. Great experience.,NaN,NaN,Vacation,Family,NaN,NaN,NaN,NaN,https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sCi9DQUlRQUNvZENodHljRjlvT25scllXTmZRa0ZtVEZSVlMyNXNRek5STW1GeWIxRRAB!2m1!1s0x0:0x3e406fbb8226738e!3m1!1s2@1:CAIQACodChtycF9oOnlrYWNfQkFmTFRVS25sQzNRMmFyb1E%7C%7C?hl=en,5.0,1780505140,06/03/2026 16:45:40,NaN,4485708079994139534,NaN,NaN,NaN,NaN,NaN,Luxury,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
# Columnas que conservamos del corpus
columnas_deseadas = [
    'review_text',
    'review_rating',
    'category',
    'reviews_link',
    'name',
    'review_datetime_utc',
    'review_questions_Travel group'
]

# Revisamos cuáles existen realmente en el Corpus
columnas_presentes = [col for col in columnas_deseadas if col in df.columns]
columnas_faltantes = [col for col in columnas_deseadas if col not in df.columns]

if columnas_faltantes:
    print("Columnas no encontradas en el corpus y que no se conservarán:")
    for col in columnas_faltantes:
        print(f"  - {col}")

# Filtramos el Corpus para que solo tenga las columnas presentes
df = df[columnas_presentes].copy()

print("\nColumnas conservadas:")
print(df.columns.tolist())
print(f"Dimensiones actuales: {df.shape}")
df.head(3)

Columnas conservadas:
['review_text', 'review_rating', 'category', 'reviews_link', 'name', 'review_datetime_utc', 'review_questions_Travel group']
Dimensiones actuales: (3400, 7)

,review_text,review_rating,category,reviews_link,name,review_datetime_utc,review_questions_Travel group
0,"We just did the hot springs and slides for the day. The water slides are crazy awesome, even the kids toilet bowl slide was more extreme than we get in the States. Laying in the top hot spring during a downpour was amazing.",5.0,Hotel,https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,Baldi Hot Springs Hotel Resort & Spa,06/07/2026 00:48:58,Friends
1,"I read a lot of negative reviews a few days before we arrived, and I was outside the cancelation window, so we had to make the best of it.\r\nThis place is amazing! We stayed 3 nights 6/1-6/4. The resort is very well maintained and clean. The check in process was very easy. They accepted.credit card (did not require bank transfer) and allowed us to call our credit card and authorize international charges. They were patient and accommodating. Everyone we met was friendly and helpful. The rooms are huge and nice! They had robes, shaving kit, dental kit, sewing kit, lotion, shampoo, and conditioner. The room had coffee! Great patio area! We booked 2 and had connecting rooms.\r\nThe hot springs were not busy or over crowded. It rained every day, sometimes showers or torrential downpour. The breakfast was okay, not a huge selection but enough to satisfy everyone in our party. We got a couple burgers one night ($14.50 each) they were decent. The last night we got some dishes to take back to the room. (Fettuccine alfredo, nachos, Mediterranean salad). The salad with grilled chicken, candied nuts, fresh vegetables was delicious. My 7 year old barely let me get a bite.\r\nThere is a small market if you walk outside to the right, you can grab alcohol, snacks, candy etc. Soda Typical is also there we got chicken quesadillas ($8) and an amazing hamburger for $9.\r\nCheck out was simple, we called and asked to send the cart at 10:30 as we had transportation picking us up at 11. The front desk was friendly and told us to wait a few minutes while they checked the room. (We travel often and this is normal so we were prepared, I read they care about towels, robes, and umbrellas, so I had everything laying out in piles). It took 5 minutes max! They cut off the bands printed our bill and there were not any extra or hidden charges.\r\nThey do sell alcohol and it ranges from $11-20 a drink. You can put it on a card or pay cash. Expect normal American prices at the resort. The workers glady accept tips but the new credit card software does not allow you to tip (just as an fyi). The slides-watch people go down them and ask about their experience before allowing your children or self to try. There were 2 that I Did not allow my 7 year old on (the blue and yellow one near kids area and the middle one (serpentine) with the group of slides. All others they loved.\r\nOverall amazing experience.",5.0,Hotel,https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,Baldi Hot Springs Hotel Resort & Spa,06/04/2026 17:40:19,Family
2,This resort was amazing. We had two different rooms in different buildings. To check in was very easy. The hot springs were incredible and so many to try. The grounds were beyond lush. Great location near town. Very helpful and friendly staff. Luxury linens in the rooms including pooll towels. The breakfast buffet was included with our room and was delicious every morning. Great experience.,5.0,Hotel,https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,Baldi Hot Springs Hotel Resort & Spa,06/03/2026 16:45:40,Family

In [40]:
# Duplicados considerando todas las columnas
duplicados_completos = df.duplicated()
total_duplicados = duplicados_completos.sum()

print(f"Total de filas duplicadas exactas (todas las columnas): {total_duplicados}")
if total_duplicados > 0:
    print("\nPrimeros 5 duplicados:")
    display(df[duplicados_completos].head(5))
else:
    print("No se encontraron filas completamente duplicadas.")

Total de filas duplicadas exactas (todas las columnas): 0
No se encontraron filas completamente duplicadas.

In [41]:
# Detectar filas donde todas las columnas son NaN o vacías
filas_totalmente_vacias = df.isnull().all(axis=1) | (df.astype(str).apply(lambda x: x.str.strip() == '', axis=1).all(axis=1))

total_filas_vacias = filas_totalmente_vacias.sum()

print(f"Total de filas completamente vacías: {total_filas_vacias}")

if total_filas_vacias > 0:
    print("\nÍndices de las filas vacías:")
    print(df[filas_totalmente_vacias].index.tolist())

    # Eliminar filas completamente vacías
    df = df[~filas_totalmente_vacias].copy()

    print(f"\n Filas eliminadas. Nuevo tamaño del dataset: {df.shape}")
else:
    print("No se encontraron filas completamente vacías.")

Total de filas completamente vacías: 0
No se encontraron filas completamente vacías.

In [42]:
# Diccionario con el mapeo de nombres
mapeo_nombres = {
    'review_text': 'reseña',
    'review_rating': 'calificación',
    'category': 'tipo_lugar',
    'reviews_link': 'fuente',
    'name': 'nombre',
    'review_datetime_utc': 'fecha',
    'review_questions_Travel group': 'grupo_de_viaje'
}

# Renombramos solo las columnas que existen en el DataFrame
df.rename(columns={k: v for k, v in mapeo_nombres.items() if k in df.columns}, inplace=True)

print("Columnas renombradas:")
print(df.columns.tolist())
df.head(3)

Columnas renombradas:
['reseña', 'calificación', 'tipo_lugar', 'fuente', 'nombre', 'fecha', 'grupo_de_viaje']

,reseña,calificación,tipo_lugar,fuente,nombre,fecha,grupo_de_viaje
0,"We just did the hot springs and slides for the day. The water slides are crazy awesome, even the kids toilet bowl slide was more extreme than we get in the States. Laying in the top hot spring during a downpour was amazing.",5.0,Hotel,https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,Baldi Hot Springs Hotel Resort & Spa,06/07/2026 00:48:58,Friends
1,"I read a lot of negative reviews a few days before we arrived, and I was outside the cancelation window, so we had to make the best of it.\r\nThis place is amazing! We stayed 3 nights 6/1-6/4. The resort is very well maintained and clean. The check in process was very easy. They accepted.credit card (did not require bank transfer) and allowed us to call our credit card and authorize international charges. They were patient and accommodating. Everyone we met was friendly and helpful. The rooms are huge and nice! They had robes, shaving kit, dental kit, sewing kit, lotion, shampoo, and conditioner. The room had coffee! Great patio area! We booked 2 and had connecting rooms.\r\nThe hot springs were not busy or over crowded. It rained every day, sometimes showers or torrential downpour. The breakfast was okay, not a huge selection but enough to satisfy everyone in our party. We got a couple burgers one night ($14.50 each) they were decent. The last night we got some dishes to take back to the room. (Fettuccine alfredo, nachos, Mediterranean salad). The salad with grilled chicken, candied nuts, fresh vegetables was delicious. My 7 year old barely let me get a bite.\r\nThere is a small market if you walk outside to the right, you can grab alcohol, snacks, candy etc. Soda Typical is also there we got chicken quesadillas ($8) and an amazing hamburger for $9.\r\nCheck out was simple, we called and asked to send the cart at 10:30 as we had transportation picking us up at 11. The front desk was friendly and told us to wait a few minutes while they checked the room. (We travel often and this is normal so we were prepared, I read they care about towels, robes, and umbrellas, so I had everything laying out in piles). It took 5 minutes max! They cut off the bands printed our bill and there were not any extra or hidden charges.\r\nThey do sell alcohol and it ranges from $11-20 a drink. You can put it on a card or pay cash. Expect normal American prices at the resort. The workers glady accept tips but the new credit card software does not allow you to tip (just as an fyi). The slides-watch people go down them and ask about their experience before allowing your children or self to try. There were 2 that I Did not allow my 7 year old on (the blue and yellow one near kids area and the middle one (serpentine) with the group of slides. All others they loved.\r\nOverall amazing experience.",5.0,Hotel,https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,Baldi Hot Springs Hotel Resort & Spa,06/04/2026 17:40:19,Family
2,This resort was amazing. We had two different rooms in different buildings. To check in was very easy. The hot springs were incredible and so many to try. The grounds were beyond lush. Great location near town. Very helpful and friendly staff. Luxury linens in the rooms including pooll towels. The breakfast buffet was included with our room and was delicious every morning. Great experience.,5.0,Hotel,https://search.google.com/local/reviews?placeid=ChIJOTLytwcMoI8RjnMmgrtvQD4&q=*&authuser=0&hl=en&gl=US,Baldi Hot Springs Hotel Resort & Spa,06/03/2026 16:45:40,Family

In [43]:
# Usamos .map en lugar de .applymap
df = df.map(lambda x: x.lower() if isinstance(x, str) else x)

print("Todas las celdas de texto han sido convertidas a minúsculas.")
df.head(3)

Todas las celdas de texto han sido convertidas a minúsculas.

,reseña,calificación,tipo_lugar,fuente,nombre,fecha,grupo_de_viaje
0,"we just did the hot springs and slides for the day. the water slides are crazy awesome, even the kids toilet bowl slide was more extreme than we get in the states. laying in the top hot spring during a downpour was amazing.",5.0,hotel,https://search.google.com/local/reviews?placeid=chijotlytwcmoi8rjnmmgrtvqd4&q=*&authuser=0&hl=en&gl=us,baldi hot springs hotel resort & spa,06/07/2026 00:48:58,friends
1,"i read a lot of negative reviews a few days before we arrived, and i was outside the cancelation window, so we had to make the best of it.\r\nthis place is amazing! we stayed 3 nights 6/1-6/4. the resort is very well maintained and clean. the check in process was very easy. they accepted.credit card (did not require bank transfer) and allowed us to call our credit card and authorize international charges. they were patient and accommodating. everyone we met was friendly and helpful. the rooms are huge and nice! they had robes, shaving kit, dental kit, sewing kit, lotion, shampoo, and conditioner. the room had coffee! great patio area! we booked 2 and had connecting rooms.\r\nthe hot springs were not busy or over crowded. it rained every day, sometimes showers or torrential downpour. the breakfast was okay, not a huge selection but enough to satisfy everyone in our party. we got a couple burgers one night ($14.50 each) they were decent. the last night we got some dishes to take back to the room. (fettuccine alfredo, nachos, mediterranean salad). the salad with grilled chicken, candied nuts, fresh vegetables was delicious. my 7 year old barely let me get a bite.\r\nthere is a small market if you walk outside to the right, you can grab alcohol, snacks, candy etc. soda typical is also there we got chicken quesadillas ($8) and an amazing hamburger for $9.\r\ncheck out was simple, we called and asked to send the cart at 10:30 as we had transportation picking us up at 11. the front desk was friendly and told us to wait a few minutes while they checked the room. (we travel often and this is normal so we were prepared, i read they care about towels, robes, and umbrellas, so i had everything laying out in piles). it took 5 minutes max! they cut off the bands printed our bill and there were not any extra or hidden charges.\r\nthey do sell alcohol and it ranges from $11-20 a drink. you can put it on a card or pay cash. expect normal american prices at the resort. the workers glady accept tips but the new credit card software does not allow you to tip (just as an fyi). the slides-watch people go down them and ask about their experience before allowing your children or self to try. there were 2 that i did not allow my 7 year old on (the blue and yellow one near kids area and the middle one (serpentine) with the group of slides. all others they loved.\r\noverall amazing experience.",5.0,hotel,https://search.google.com/local/reviews?placeid=chijotlytwcmoi8rjnmmgrtvqd4&q=*&authuser=0&hl=en&gl=us,baldi hot springs hotel resort & spa,06/04/2026 17:40:19,family
2,this resort was amazing. we had two different rooms in different buildings. to check in was very easy. the hot springs were incredible and so many to try. the grounds were beyond lush. great location near town. very helpful and friendly staff. luxury linens in the rooms including pooll towels. the breakfast buffet was included with our room and was delicious every morning. great experience.,5.0,hotel,https://search.google.com/local/reviews?placeid=chijotlytwcmoi8rjnmmgrtvqd4&q=*&authuser=0&hl=en&gl=us,baldi hot springs hotel resort & spa,06/03/2026 16:45:40,family

In [44]:
# Dividimos por el espacio y nos quedamos con la primera parte (la fecha)
df['fecha'] = df['fecha'].str.split(' ').str[0]

print("Fechas limpiadas. Ejemplos:")
df[['fecha']].head(10)

Fechas limpiadas. Ejemplos:

        fecha
0  06/07/2026
1  06/04/2026
2  06/03/2026
3  06/03/2026
4  06/03/2026
5  05/31/2026
6  05/31/2026
7  05/31/2026
8  05/31/2026
9  05/31/2026

In [46]:
# Condición: reseña es nula, vacía o contiene solo espacios
condicion_vacia = df['reseña'].isna() | (df['reseña'].str.strip() == '')

total_vacias = condicion_vacia.sum()
print(f"Total de reseñas vacías: {total_vacias}")

if total_vacias > 0:
    # Mostrar algunos ejemplos de las filas que se eliminarán
    print("\nPrimeras 5 filas con reseña vacía:")
    display(df[condicion_vacia].head(5))

    # Eliminar esas filas
    df = df[~condicion_vacia].copy()

    print(f"\n Filas eliminadas. Nuevo tamaño del dataset: {df.shape}")
else:
    print("No se encontraron reseñas vacías.")

Total de reseñas vacías: 0
No se encontraron reseñas vacías.

In [15]:
!pip install langdetect

Requirement already satisfied: langdetect in c:\users\ferna\anaconda3\lib\site-packages (1.0.9)
Requirement already satisfied: six in c:\users\ferna\anaconda3\lib\site-packages (from langdetect) (1.16.0)

In [47]:
from langdetect import detect, LangDetectException
import numpy as np

def detectar_espanol(texto):
    try:
        return detect(texto) == 'es'
    except LangDetectException:
        # Si falla (por texto muy corto, solo números, etc.), lo consideramos no español
        return False

# Aplicamos la detección a la columna 'reseña'
print("Detectando idiomas... (puede tardar unos segundos)")
es_espanol = df['reseña'].apply(detectar_espanol)

# Contar resultados
total_no_espanol = (~es_espanol).sum()
print(f"Reseñas que NO están en español: {total_no_espanol}")

if total_no_espanol > 0:
    print("\nEjemplos de reseñas eliminadas (primeras 5):")
    display(df[~es_espanol][['reseña']].head(5))

# Filtrar solo las que son español
df = df[es_espanol].copy()

print(f"\nReseñas en español conservadas. Nuevo tamaño: {df.shape}")

Detectando idiomas... (puede tardar unos segundos)
Reseñas que NO están en español: 1699

Ejemplos de reseñas eliminadas (primeras 5):

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       reseña
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             we just did the hot springs and slides for the day. the water slides are crazy awesome, even the kids toilet bowl slide was more extreme than we get in the states. laying in the top hot spring during a downpour was amazing.
1  i read a lot of negative reviews a few days before we arrived, and i was outside the cancelation window, so we had to make the best of it.\r\nthis place is amazing! we stayed 3 nights 6/1-6/4. the resort is very well maintained and clean. the check in process was very easy. they accepted.credit card (did not require bank transfer) and allowed us to call our credit card and authorize international charges. they were patient and accommodating.  everyone we met was friendly and helpful. the rooms are huge and nice! they had robes, shaving kit, dental kit, sewing kit, lotion, shampoo, and conditioner. the room had coffee! great patio area! we booked 2 and had connecting rooms.\r\nthe hot springs were not busy or over crowded. it rained every day, sometimes showers or torrential downpour. the breakfast was okay, not a huge selection but enough to satisfy everyone in our party. we got a couple burgers one night ($14.50 each) they were decent. the last night we got some dishes to take back to the room. (fettuccine alfredo, nachos, mediterranean salad). the salad with grilled chicken, candied nuts, fresh vegetables was delicious. my 7 year old barely let me get a bite.\r\nthere is a small market if you walk outside to the right, you can grab alcohol, snacks, candy etc. soda typical is also there we got chicken quesadillas ($8) and an amazing hamburger for $9.\r\ncheck out was simple, we called and asked to send the cart at 10:30 as we had transportation picking us up at 11. the front desk was friendly and told us to wait a few minutes while they checked the room. (we travel often and this is normal so we were prepared, i read they care about towels, robes, and umbrellas, so i had everything laying out in piles). it took 5 minutes max! they cut off the bands printed our bill and there were not any extra or hidden charges.\r\nthey do sell alcohol and it ranges from $11-20 a drink. you can put it on a card or pay cash. expect normal american prices at the resort. the workers glady accept tips but the new credit card software does not allow you to tip (just as an fyi). the slides-watch people go down them and ask about their experience before allowing your children or self to try. there were 2 that i did not allow my 7 year old on (the blue and yellow one near kids area and the middle one (serpentine) with the group of slides. all others they loved.\r\noverall amazing experience.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   this resort was amazing. we had two different rooms in different buildings. to check in was very easy. the hot springs were incredible and so many to try. the grounds were beyond lush. great location near town. very helpful and friendly staff. luxury linens in the rooms including pooll towels. the breakfast buffet was included with our room and was delicious every morning. great experience.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          price is the major factor,  one drink here is 20-25 usd! !  let alone 50 a person to enter.\r\npros. probably the best water slides out of all (27mph)! great variety, hot to warm with a couple cool pools. a fun younger child section. great vibe & natural feel for great photos. lockers cost you but not really needed if you carry a water bag around and move it along as you go. can rent towels for a returned deposit.  more a fashion statement place.
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                great place.. it's wonderful

Reseñas en español conservadas. Nuevo tamaño: (785, 7)

In [48]:
import re
def eliminar_emojis(texto):
    if not isinstance(texto, str):
        return ""
    # Elimina emojis y símbolos no latinos, conservando letras acentuadas, puntuación básica, espacios
    texto_limpio = re.sub(r'[^\w\s.,!?;:áéíóúüñÁÉÍÓÚÜÑ]', '', texto, flags=re.UNICODE)
    # Normalizar espacios múltiples
    texto_limpio = re.sub(r'\s+', ' ', texto_limpio).strip()
    return texto_limpio

In [49]:
import re

def limpiar_caracteres_especiales(texto):
    """
    Conserva solo:
      - Letras (incluyendo acentos, diéresis y ñ/Ñ)
      - Números (0-9)
      - Espacios
    Elimina todo lo demás: puntuación, símbolos, etc.
    """
    if not isinstance(texto, str):
        return ""

    # Mantiene solo letras (incluye tildes y ñ), números y espacios
    texto = re.sub(r'[^a-záéíóúüñA-ZÁÉÍÓÚÜÑ0-9\s]', '', texto, flags=re.UNICODE)

    # Normaliza espacios múltiples y recorta extremos
    texto = re.sub(r'\s+', ' ', texto).strip()

    return texto

# Aplicar la limpieza
df['reseña'] = df['reseña'].apply(limpiar_caracteres_especiales)

# Verificar si alguna reseña quedó vacía después de la limpieza
vacias_post_limpieza = (df['reseña'] == '') | df['reseña'].isna()
total_vacias_post = vacias_post_limpieza.sum()
print(f"Reseñas vacías después de la limpieza: {total_vacias_post}")

if total_vacias_post > 0:
    df = df[~vacias_post_limpieza].copy()
    print(f"Filas eliminadas. Nuevo tamaño: {df.shape}")

# Mostrar ejemplos
print("\nEjemplos de reseñas completamente limpias:")
df[['reseña']].head(5)

Reseñas vacías después de la limpieza: 0

Ejemplos de reseñas completamente limpias:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           reseña
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fue una pésima experiencia llegamos solo por una noche porque íbamos de paso nada más y a la hora de realizar el chek out nos hicieron el cobro de una toalla que ni siquiera pusieron en nuestra habitación simplemente fue inaudito pagar por algo que ellos ni siquiera nos dieron pero bueno en fin ellos igual te lo van a cobrar porque según las políticas del hotel la culpa siempre es del cliente y no de su personal que tal vez no revisó bien así que como recomendación mejor cuenten sus toallas y revisen su habitación apenas llegan porque sino les van a cobrar demás por cualquier incidente y no te van a brindar solución muy mal experiencia y muy mal servicio al cliente
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        todo muy bonito realmente me quedo sin palabras con tan semejante lugar
23  una experiencia relajante e imperdible en costa rica si visitas la zona del arenal baldí hot springs es una parada obligatoria lo que más me fascinó de este lugar es la gran variedad de piscinas termales que ofrece cada una tiene su propia temperatura y como regla general entre más cerca estés del volcán más caliente se siente el agua esto te permite explorar y encontrar el punto exacto de calor que más te guste en nuestro caso decidimos pasar la mayor parte del tiempo en la tercera piscina y fue una excelente elección tiene un ambiente increíble porque ahí mismo se encuentran los toboganes un restaurante y un wet bar bar dentro de la piscina lo que hace que la experiencia sea súper cómoda y divertida sin tener que salir del agua el horario me pareció perfecto para disfrutarlo por la tarde nosotros llegamos a las 500 pm y el lugar cierra hasta las 1000 pm esas 5 horas son el tiempo ideal para sumergirse relajarse por completo y no sentir el paso del tiempo además de las piscinas el sauna me gustó muchísimo está muy bien logrado y complementa perfecto el circuito de relajación para cerrar la noche con broche de oro al salir de las piscinas nos relajamos comiendo una buena pizza acompañada de una cerveza bien fría sin duda considero que son de las mejores aguas termales de costa rica totalmente recomendado para ir a relajarse y pasar un rato inolvidable
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        buena experiencia nos habían recomendado en gran parte del viaje este lugar por lo que decidimos pasar la tarde de nuestra llegada a la fortuna en el area de termas cuentan con una amplia variedad de piscinas con agua de diferentes temperaturas algunas con cascadas otras con bares en el interior de la piscina y otras con toboganes el espacio está muy bien cuidado la vegetación es abundante y hay facil acceso a duchas baños y camarines todo muy limpio el trato de todos quienes nos atendieron fue muy amable la única nota baja fue la alimentación se ofrece tipo buffet pero la verdad la variedad y la calidad deja bastante que desear habriamos estado dispuestos a pagar un poco más incluso de saber como sería es un lugar bastante concurrido por lo que quizás no es lo óptimo para relajarse totalmente pero de todas formas lo recomiendo
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        un gran lugar para hospedarse un pasasar un rato agradable cuenta con varias albercas con distintas temperaturas de mas caliente a mas fría limpias baños limpios andadores y toboganes

In [31]:
!pip install pyspellchecker

Requirement already satisfied: pyspellchecker in c:\users\ferna\anaconda3\lib\site-packages (0.9.0)

In [50]:
from spellchecker import SpellChecker
import pandas as pd

# Crear el corrector en español
spell = SpellChecker(language='es')

def contar_errores(texto):
    """Cuenta las palabras que no están en el diccionario."""
    if not isinstance(texto, str) or texto.strip() == '':
        return 0
    palabras = texto.split()
    # Palabras que el corrector considera erróneas
    desconocidas = spell.unknown(palabras)
    return len(desconocidas)

def palabras_erroneas(texto):
    """Devuelve una lista de las palabras probablemente mal escritas."""
    if not isinstance(texto, str) or texto.strip() == '':
        return []
    palabras = texto.split()
    desconocidas = spell.unknown(palabras)
    return list(desconocidas)

# Aplicar a cada reseña
print("Analizando errores (puede tardar unos segundos)...")
df['cantidad_errores'] = df['reseña'].apply(contar_errores)
df['palabras_erroneas'] = df['reseña'].apply(palabras_erroneas)

# Resumen estadístico
total_resenas = len(df)
resenas_con_errores = (df['cantidad_errores'] > 0).sum()
print(f"\nTotal de reseñas: {total_resenas}")
print(f"Reseñas con al menos un posible error: {resenas_con_errores} ({100*resenas_con_errores/total_resenas:.1f}%)")

# Mostrar algunas reseñas con más errores
top_erroneas = df.nlargest(10, 'cantidad_errores')[['reseña', 'cantidad_errores', 'palabras_erroneas']]
print("\nLas 10 reseñas con más posibles errores ortográficos:")
for i, row in top_erroneas.iterrows():
    print(f"\nReseña (errores: {row['cantidad_errores']}):")
    print(row['reseña'][:200] + ('...' if len(row['reseña']) > 200 else ''))
    print(f"Palabras dudosas: {row['palabras_erroneas'][:15]}...")

Analizando errores (puede tardar unos segundos)...

Total de reseñas: 785
Reseñas con al menos un posible error: 670 (85.4%)

Las 10 reseñas con más posibles errores ortográficos:

Reseña (errores: 118):
la experiencia en general estuvo bien y el hotel tiene varios puntos positivos que disfrutamos las piscinas son muy bonitas amplias y agradables para pasar el día uno de los aspectos que más nos gustó...
Palabras dudosas: ['pasó', 'mejores', 'cambiarlas', 'atendernos', 'baños', 'bonitas', 'disfrutamos', 'deberían', 'audífonos', 'cambiarnos', 'piscinas', 'ensaladas', 'amables', 'detalles', 'reponiendo']...

Reseña (errores: 93):
ubicado en una de esas zonas modernas y vidriadas que podrían ser puerto madero en buenos aires o cualquier barrio cosmopolita de una gran ciudad si uno se despertara allí sin contexto podría creer qu...
Palabras dudosas: ['despertara', 'resueltos', 'concesiones', 'aceptó', 'parece', 'vidriadas', 'dónde', 'eligió', 'mesas', 'pies', 'modernas', 'abraza', 'show', 'cae', 'funciona']...

Reseña (errores: 77):
lamento decir que para mi y mi pareja fu una mala experiencia gastronomica empezando desde la llegada nos recibi una chica con lentesnosotros no teniamos reservaella fu a verificar que hubiera una mes...
Palabras dudosas: ['libres', 'carpaccio', 'experienciaseguros', 'llev', 'llegamos', 'vuelva', 'buenovegetales', 'tragos', 'mejorpero', 'discriminatorio', 'otras', 'quieriamos', 'barracuando', 'empezando', 'habian']...

Reseña (errores: 70):
estancia de 7 días con familia desde nuestra llegada nos encontramos con algunos inconvenientes que afectaron la experiencia que esperábamos al entrar a nuestra habitación notamos que las sábanas esta...
Palabras dudosas: ['serviciopor', 'supervisión', 'tablas', 'tuvimos', 'esperábamos', 'sufrimos', 'resultó', 'ofrecen', 'atendidos', 'puntos', 'aclararlo', 'afectaron', 'estaban', 'lácteos', 'amenidades']...

Reseña (errores: 64):
estuvimos hospedados 3 noches en el hotel en una habitación junior suite desde el día 11 hasta el sábado 14 de marzo de 2026 he ido en 4 ocasiones en los últimos años el hotel como desde la primera ve...
Palabras dudosas: ['años', 'invierten', 'out', 'urinarios', 'estuvimos', 'tiene', 'baños', 'dice', 'pague', 'ganas', 'dejadísimos', 'valen', 'reírse', 'masculinos', 'desayunar']...

Reseña (errores: 64):
un lugar espectacular y sin duda una visita obligada para cualquiera que viaje a manuel antonio el parque está muy bien mantenido los senderos principales son cómodos de recorrer y todo se encuentra e...
Palabras dudosas: ['guías', 'playas', 'antonio', 'tuvimos', 'quienes', 'condiciones', 'unos', 'mejores', 'mantenido', 'estuvimos', 'ocurre', 'oficiales', 'detenerse', 'puede', 'opciones']...

Reseña (errores: 54):
le he dado 2 oportunidades pensando que tal vez fue mala suerte o un mal día pero definitivamente no veo el valor de su menú la primera vez que fui hace un tiempo pedí un pescado al vapor en hoja de p...
Palabras dudosas: ['sabía', 'opacaba', 'extranjeros', 'hace', 'mini', 'llegó', 'turistas', 'restaurantes', 'marketing', 'camarones', 'esperando', 'menú', 'achiotada', 'tartar', 'oportunidades']...

Reseña (errores: 51):
es un lugar muy bonito las piscinas son amplias así que no estás tan cerca de otras personas la comida estuvo bien no deliciosa pero bien quise almorzar y cenar pero solamente había espacio para el al...
Palabras dudosas: ['qué', 'mandan', 'dejen', 'quise', 'contaminante', 'recomiendo', 'ví', 'cómo', 'especies', 'visito', 'ornamentales', 'sé', 'amplias', 'estuvo', 'deberían']...

Reseña (errores: 49):
al parecer es uno de los parques nacionales menos visitados y menos atractivos para los que le gusta la aventura extrema senderos cortos y sin pendientes son de nivel muy principiante el lugar es idea...
Palabras dudosas: ['demorado', 'debes', 'dice', 'atractivos', 'recomiendo', 'creo', 'ultimo', 'dijo', 'avistamiento', 'tuve', 'visitados', 'parques', 'youtube', 'niños', 'super']...

Reseña (errores: 48):
secrets papagayo costa rica es un lugar verdaderamente especial su mayor encanto está en su entorno una playa tranquila rodeada de montañas vegetación exuberante y fauna local que te hace sentir compl...
Palabras dudosas: ['cuartos', 'memorables', 'vive', 'actividades', 'buffet', 'hace', 'desconectado', 'pensados', 'cuidando', 'puedes', 'ganas', 'opciones', 'diferentes', 'adriana', 'aún']...

Los errores más comunes que cometen las personas a la hora de dejar su reseña en el sitio de google maps son:
1. Escribir las palabras pegadas haciendo que no tenga sentido el texto sin la debida separación
2. Tener bastantes errores ortográficos (confundiendo u omitiendo letras)
3. Repitiendo las mismas palabras una al lado de la otra

In [51]:
# Eliminar las columnas agregadas por el análisis de ortografía
columnas_a_eliminar = ['cantidad_errores', 'palabras_erroneas']

# Solo eliminamos las que realmente existen para evitar errores
df.drop(columns=[col for col in columnas_a_eliminar if col in df.columns], inplace=True)

print("Columnas eliminadas. Columnas actuales:")
print(df.columns.tolist())

Columnas eliminadas. Columnas actuales:
['reseña', 'calificación', 'tipo_lugar', 'fuente', 'nombre', 'fecha', 'grupo_de_viaje']

In [52]:
# Convertir calificación a entero (maneja valores nulos)
df['calificación'] = pd.to_numeric(df['calificación'], errors='coerce').astype('Int64')

# Verificar los valores únicos y sus tipos
print("Valores únicos en calificación:")
print(df['calificación'].unique())
print(f"\nTipo de dato: {df['calificación'].dtype}")

# Mostrar algunos ejemplos
df[['calificación']].head(10)

Valores únicos en calificación:
<IntegerArray>
[1, 5, 4, 3, 2]
Length: 5, dtype: Int64

Tipo de dato: Int64

    calificación
16             1
22             5
23             5
24             4
26             5
41             5
42             5
50             1
51             5
55             5

In [53]:
# Mostrar todos los valores únicos y su frecuencia
print("Valores únicos en 'grupo_de_viaje' y su cantidad:")
print(df['grupo_de_viaje'].value_counts(dropna=False))

Valores únicos en 'grupo_de_viaje' y su cantidad:
grupo_de_viaje
NaN        676
family      44
couple      33
friends     22
solo        10
Name: count, dtype: int64

In [54]:
# Diccionario de traducción
mapeo_grupo = {
    'family': 'familia',
    'couple': 'pareja',
    'friends': 'amigos'
    # 'solo' se queda igual, NaN no se toca
}

# Reemplazar solo los valores que están en el diccionario
df['grupo_de_viaje'] = df['grupo_de_viaje'].replace(mapeo_grupo)

print("Valores actualizados. Conteo final:")
print(df['grupo_de_viaje'].value_counts(dropna=False))

Valores actualizados. Conteo final:
grupo_de_viaje
NaN        676
familia     44
pareja      33
amigos      22
solo        10
Name: count, dtype: int64

In [55]:
# Guardar el DataFrame actual como CSV en data/processed/
ruta_salida = proyecto / 'data' / 'processed' / 'resenas_clean.csv'
ruta_salida.parent.mkdir(parents=True, exist_ok=True)  # crea la carpeta si no existe
df.to_csv(ruta_salida, index=False)

print(f"Dataset limpio guardado en: {ruta_salida}")
print(f"Dimensiones: {df.shape}")

Dataset limpio guardado en: C:\Reseñas_turisticas_CR\Rese-as-turisticas\data\processed\resenas_clean.csv
Dimensiones: (785, 7)

In [30]:
import os

ruta_descarga = os.path.join(os.path.expanduser("~"), "Downloads", "resenas_clean.csv")
df.to_csv(ruta_descarga, index=False)

print(f"✅ Archivo guardado en: {ruta_descarga}")

✅ Archivo guardado en: C:\Users\ferna\Downloads\resenas_clean.csv