In [1]:
import pandas as pd
from pathlib import Path
import os

print("Directorio de trabajo actual:")
print(os.getcwd())

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\ferna\AppData\Local\Temp\ipykernel_32688\312789154.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\__init__.py", line 34, in <module>
    from pandas.compat import (
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 28, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 9, in <module>
    import pyarrow as pa
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\ferna\AppData\Local\Temp\ipykernel_32688\312789154.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 28, in <module>
    from pandas._libs import (
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\ferna\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\ferna\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\ferna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\ferna\AppData\Local\Temp\ipykernel_32688\312789154.py", line 1, in <module>
    import pandas as pd
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 79, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 56, in <module>
    from pandas.core import (
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 54, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\ferna\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\ferna\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ferna\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Directorio de trabajo actual:
C:\Reseñas_turisticas_CR\Rese-as-turisticas\notebooks

In [2]:
raiz = Path.cwd()
print("\nContenido de la carpeta actual (donde se ejecuta Jupyter):")
for elemento in raiz.iterdir():
    print("  ", elemento.name)

Contenido de la carpeta actual (donde se ejecuta Jupyter):
   01_exploracion_datos.ipynb
   02_pos_tagging_nltk.ipynb
   03_pos_tagging_spacy.ipynb
   04_analisis_morfologico.ipynb
   05_comparacion_polaridad.ipynb
   06_comparacion_lugares.ipynb
   07_visualizaciones.ipynb
   limpieza.ipynb
   limpieza_verificacion.ipynb

In [3]:
# Busca el directorio del proyecto subiendo niveles hasta encontrar la carpeta 'data'
proyecto = Path.cwd()
while not (proyecto / 'data').exists() and proyecto.parent != proyecto:
    proyecto = proyecto.parent

if (proyecto / 'data').exists():
    print("Carpeta 'data' encontrada en:", proyecto)
else:
    print("ERROR: no se encontró la carpeta 'data' en ningún nivel superior.")

Carpeta 'data' encontrada en: C:\Reseñas_turisticas_CR\Rese-as-turisticas

In [4]:
ruta_data = proyecto / 'data'
ruta_raw = ruta_data / 'raw'
print("¿Existe data/raw?:", ruta_raw.exists())

if ruta_raw.exists():
    print("\nContenido de data/raw:")
    for elemento in ruta_raw.iterdir():
        tipo = "📁" if elemento.is_dir() else "📄"
        print(f"  {tipo} {elemento.name}")
else:
    print("La carpeta 'raw' no existe. Revisá la estructura manualmente.")

¿Existe data/raw?: True

Contenido de data/raw:
  📄 Baldi.xlsx
  📄 Barceló Tambor.xlsx
  📁 final
  📄 Furca Restaurant, San José, Costa Rica.xlsx
  📄 Gran Hotel Costa Rica.xlsx
  📄 Grano de Oro Restaurant, San José, Costa Rica.xlsx
  📄 Hotel Costa Rica Marriott Hacienda Belén.xlsx
  📄 Hotel Grano de Oro.xlsx
  📄 Hotel Riu Guanacaste.xlsx
  📄 La Divina Comida, San José, Costa Rica.xlsx
  📄 Nayara Gardens.xlsx
  📄 Parque Nacional Cahuita, Costa Rica.xlsx
  📄 Parque Nacional Carara, Costa Rica.xlsx
  📄 Parque Nacional Corcovado, Costa Rica.xlsx
  📄 Parque Nacional Manuel Antonio, Costa Rica.xlsx
  📄 Parque Nacional Marino Ballena, Costa Rica.xlsx
  📄 Parque Nacional Rincón de la Vieja, Costa Rica.xlsx
  📄 Parque Nacional Santa Rosa, Costa Rica.xlsx
  📄 Parque Nacional Tortuguero, Costa Rica.xlsx
  📄 Parque Nacional Volcán Irazú, Costa Rica.xlsx
  📄 Parque Nacional Volcán Poás, Costa Rica.xlsx
  📄 Red Frog Coffee Roaster, La Fortuna, Costa Rica.xlsx
  📄 Restaurante El Novillo Alegre, San José, Costa Rica.xlsx
  📄 Restaurante Numu Taproom, Tamarindo, Costa Rica.xlsx
  📄 Restaurante Silvestre, San José, Costa Rica.xlsx
  📄 Secrets Papagayo Costa Rica.xlsx
  📄 Sikwa Restaurant, San José, Costa Rica.xlsx
  📄 Soda Viquez, Quepos, Costa Rica.xlsx
  📄 Tabacón Thermal Resort and Spa.xlsx
  📄 The Green Room Cafe, Jacó, Costa Rica.xlsx
  📄 The Royal Corin La Fortuna.xlsx
  📄 The Springs Resort and Spa at Arenal.xlsx

In [5]:
ruta_final = ruta_raw / 'final'
print("¿Existe data/raw/final?:", ruta_final.exists())

if ruta_final.exists():
    print("\nContenido de data/raw/final:")
    for archivo in ruta_final.iterdir():
        print("  📄", archivo.name)
else:
    print("No se encontró la carpeta 'final' dentro de data/raw.")
    # Tal vez el archivo está directamente en raw
    print("\nArchivos .csv en data/raw (por si no hay carpeta final):")
    for f in ruta_raw.glob("*.csv"):
        print("  📄", f.name)

¿Existe data/raw/final?: True

Contenido de data/raw/final:
  📄 resenas_google_maps.csv

In [6]:
# Definimos la ruta al archivo según lo que encontraste en las celdas anteriores
# (ajustala si es necesario)

if ruta_final.exists():
    archivo_csv = 'resenas_google_maps.csv'   # <-- confirmá el nombre exacto
    ruta_completa = ruta_final / archivo_csv
else:
    # Si no hay carpeta final, probamos en raw directamente
    archivo_csv = 'resenas_google_maps.csv'
    ruta_completa = ruta_raw / archivo_csv

print("Intentando cargar:", ruta_completa)
if ruta_completa.exists():
    df = pd.read_csv(ruta_completa)
    print("✅ Carga exitosa. Dimensiones:", df.shape)
    print("Columnas:", df.columns.tolist())
    df.head(3)
else:
    print("❌ El archivo NO existe en esa ruta.")
    # Última búsqueda: buscar el archivo en todo el proyecto
    print("\nBuscando 'resenas_google_maps.csv' en todo el proyecto...")
    encontrados = list(proyecto.rglob("resenas_google_maps.csv"))
    if encontrados:
        for encontrado in encontrados:
            print("  Encontrado en:", encontrado)
    else:
        print("No se encontró ningún archivo con ese nombre en el proyecto.")

Intentando cargar: C:\Reseñas_turisticas_CR\Rese-as-turisticas\data\raw\final\resenas_google_maps.csv
✅ Carga exitosa. Dimensiones: (3400, 66)
Columnas: ['query', 'name', 'category', 'google_id', 'place_id', 'location_link', 'reviews_link', 'reviews_per_score', 'reviews', 'rating', 'review_id', 'review_pagination_id', 'author_link', 'author_title', 'author_id', 'author_image', 'author_reviews_count', 'author_ratings_count', 'review_text', 'review_img_urls', 'review_img_url', 'review_questions_Trip type', 'review_questions_Travel group', 'review_photo_ids', 'owner_answer', 'owner_answer_timestamp', 'owner_answer_timestamp_datetime_utc', 'review_link', 'review_rating', 'review_timestamp', 'review_datetime_utc', 'review_likes', 'reviews_id', 'review_questions_Rooms', 'review_questions_Service', 'review_questions_Location', 'review_questions_Nearby activities', 'review_questions_Safety', 'review_questions_Hotel highlights', 'review_questions_None', 'review_questions', 'review_questions_Walkability', 'review_questions_Food & drinks', 'review_questions_Noteworthy details', 'review_questions_Food', 'review_questions_Atmosphere', 'review_questions_Meal type', 'review_questions_Price per person', 'review_questions_Noise level', 'review_questions_Wait time', 'review_questions_Group size', 'review_questions_Seating type', 'review_questions_Reservation', 'review_questions_Vegetarian options', 'review_questions_Dietary restrictions', 'review_questions_Parking space', 'review_questions_Parking options', 'review_questions_Kid-friendliness', 'review_questions_Wheelchair accessibility', 'review_questions_Parking', 'review_questions_Order type', 'review_questions_Special events', 'review_questions_Recommended dishes', 'review_questions_Special offers', '-----', '-']

In [7]:
import pandas as pd
from pathlib import Path

# Usamos la ruta ya verificada (proyecto / data / raw / final)
ruta_final = proyecto / 'data' / 'raw' / 'final'
archivo = 'resenas_google_maps.csv'          # <-- nombre corregido

df = pd.read_csv(ruta_final / archivo)

print("✅ Dataset cargado")
print("Dimensiones:", df.shape)
print("Columnas:", df.columns.tolist())
df.head(3)

✅ Dataset cargado
Dimensiones: (3400, 66)
Columnas: ['query', 'name', 'category', 'google_id', 'place_id', 'location_link', 'reviews_link', 'reviews_per_score', 'reviews', 'rating', 'review_id', 'review_pagination_id', 'author_link', 'author_title', 'author_id', 'author_image', 'author_reviews_count', 'author_ratings_count', 'review_text', 'review_img_urls', 'review_img_url', 'review_questions_Trip type', 'review_questions_Travel group', 'review_photo_ids', 'owner_answer', 'owner_answer_timestamp', 'owner_answer_timestamp_datetime_utc', 'review_link', 'review_rating', 'review_timestamp', 'review_datetime_utc', 'review_likes', 'reviews_id', 'review_questions_Rooms', 'review_questions_Service', 'review_questions_Location', 'review_questions_Nearby activities', 'review_questions_Safety', 'review_questions_Hotel highlights', 'review_questions_None', 'review_questions', 'review_questions_Walkability', 'review_questions_Food & drinks', 'review_questions_Noteworthy details', 'review_questions_Food', 'review_questions_Atmosphere', 'review_questions_Meal type', 'review_questions_Price per person', 'review_questions_Noise level', 'review_questions_Wait time', 'review_questions_Group size', 'review_questions_Seating type', 'review_questions_Reservation', 'review_questions_Vegetarian options', 'review_questions_Dietary restrictions', 'review_questions_Parking space', 'review_questions_Parking options', 'review_questions_Kid-friendliness', 'review_questions_Wheelchair accessibility', 'review_questions_Parking', 'review_questions_Order type', 'review_questions_Special events', 'review_questions_Recommended dishes', 'review_questions_Special offers', '-----', '-']

,query,name,category,google_id,place_id,location_link,reviews_link,reviews_per_score,reviews,rating,...,review_questions_Parking options,review_questions_Kid-friendliness,review_questions_Wheelchair accessibility,review_questions_Parking,review_questions_Order type,review_questions_Special events,review_questions_Recommended dishes,review_questions_Special offers,-----,-
0,0x8fa00c07b7f23239:0x3e406fbb8226738e,Baldi Hot Springs Hotel Resort & Spa,Hotel,0x8fa00c07b7f23239:0x3e406fbb8226738e,ChIJOTLytwcMoI8RjnMmgrtvQD4,https://www.google.com/maps/place/Baldi+Hot+Sp...,https://search.google.com/local/reviews?placei...,NaN,8827,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0x8fa00c07b7f23239:0x3e406fbb8226738e,Baldi Hot Springs Hotel Resort & Spa,Hotel,0x8fa00c07b7f23239:0x3e406fbb8226738e,ChIJOTLytwcMoI8RjnMmgrtvQD4,https://www.google.com/maps/place/Baldi+Hot+Sp...,https://search.google.com/local/reviews?placei...,NaN,8827,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0x8fa00c07b7f23239:0x3e406fbb8226738e,Baldi Hot Springs Hotel Resort & Spa,Hotel,0x8fa00c07b7f23239:0x3e406fbb8226738e,ChIJOTLytwcMoI8RjnMmgrtvQD4,https://www.google.com/maps/place/Baldi+Hot+Sp...,https://search.google.com/local/reviews?placei...,NaN,8827,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Columnas que queremos conservar (ajustá los nombres exactos si hace falta)
columnas_deseadas = [
    'review_text',
    'review_rating',
    'category',
    'reviews_link',
    'name',
    'review_datetime_utc',
    'review_questions_Travel group'
]

# Revisamos cuáles existen realmente en el DataFrame
columnas_presentes = [col for col in columnas_deseadas if col in df.columns]
columnas_faltantes = [col for col in columnas_deseadas if col not in df.columns]

if columnas_faltantes:
    print("⚠️ Columnas no encontradas en el dataset y que no se conservarán:")
    for col in columnas_faltantes:
        print(f"  - {col}")

# Filtramos el DataFrame para que solo tenga las columnas presentes
df = df[columnas_presentes].copy()

print("\n✅ Columnas conservadas:")
print(df.columns.tolist())
print(f"Dimensiones actuales: {df.shape}")
df.head(3)

✅ Columnas conservadas:
['review_text', 'review_rating', 'category', 'reviews_link', 'name', 'review_datetime_utc', 'review_questions_Travel group']
Dimensiones actuales: (3400, 7)

,review_text,review_rating,category,reviews_link,name,review_datetime_utc,review_questions_Travel group
0,We just did the hot springs and slides for the...,5.0,Hotel,https://search.google.com/local/reviews?placei...,Baldi Hot Springs Hotel Resort & Spa,06/07/2026 00:48:58,Friends
1,I read a lot of negative reviews a few days be...,5.0,Hotel,https://search.google.com/local/reviews?placei...,Baldi Hot Springs Hotel Resort & Spa,06/04/2026 17:40:19,Family
2,This resort was amazing. We had two different ...,5.0,Hotel,https://search.google.com/local/reviews?placei...,Baldi Hot Springs Hotel Resort & Spa,06/03/2026 16:45:40,Family

In [9]:
# Duplicados considerando TODAS las columnas
duplicados_completos = df.duplicated()
total_duplicados = duplicados_completos.sum()

print(f"Total de filas duplicadas exactas (todas las columnas): {total_duplicados}")
if total_duplicados > 0:
    print("\nPrimeros 5 duplicados:")
    display(df[duplicados_completos].head(5))
else:
    print("No se encontraron filas completamente duplicadas.")

Total de filas duplicadas exactas (todas las columnas): 0
No se encontraron filas completamente duplicadas.

In [10]:
# Detectar filas donde TODAS las columnas son NaN o vacías
filas_totalmente_vacias = df.isnull().all(axis=1) | (df.astype(str).apply(lambda x: x.str.strip() == '', axis=1).all(axis=1))

total_filas_vacias = filas_totalmente_vacias.sum()

print(f"Total de filas completamente vacías: {total_filas_vacias}")

if total_filas_vacias > 0:
    print("\nÍndices de las filas vacías:")
    print(df[filas_totalmente_vacias].index.tolist())

    # Eliminar filas completamente vacías
    df = df[~filas_totalmente_vacias].copy()

    print(f"\n✅ Filas eliminadas. Nuevo tamaño del dataset: {df.shape}")
else:
    print("No se encontraron filas completamente vacías.")

Total de filas completamente vacías: 0
No se encontraron filas completamente vacías.

In [11]:
# Diccionario con el mapeo de nombres
mapeo_nombres = {
    'review_text': 'reseña',
    'review_rating': 'calificación',
    'category': 'tipo_lugar',
    'reviews_link': 'fuente',
    'name': 'nombre',
    'review_datetime_utc': 'fecha',
    'review_questions_Travel group': 'grupo_de_viaje'
}

# Renombramos solo las columnas que existen en el DataFrame
df.rename(columns={k: v for k, v in mapeo_nombres.items() if k in df.columns}, inplace=True)

print("✅ Columnas renombradas:")
print(df.columns.tolist())
df.head(3)

✅ Columnas renombradas:
['reseña', 'calificación', 'tipo_lugar', 'fuente', 'nombre', 'fecha', 'grupo_de_viaje']

,reseña,calificación,tipo_lugar,fuente,nombre,fecha,grupo_de_viaje
0,We just did the hot springs and slides for the...,5.0,Hotel,https://search.google.com/local/reviews?placei...,Baldi Hot Springs Hotel Resort & Spa,06/07/2026 00:48:58,Friends
1,I read a lot of negative reviews a few days be...,5.0,Hotel,https://search.google.com/local/reviews?placei...,Baldi Hot Springs Hotel Resort & Spa,06/04/2026 17:40:19,Family
2,This resort was amazing. We had two different ...,5.0,Hotel,https://search.google.com/local/reviews?placei...,Baldi Hot Springs Hotel Resort & Spa,06/03/2026 16:45:40,Family

In [12]:
# Usamos .map en lugar de .applymap (pandas >= 2.1.0)
df = df.map(lambda x: x.lower() if isinstance(x, str) else x)

print("✅ Todas las celdas de texto han sido convertidas a minúsculas.")
df.head(3)

✅ Todas las celdas de texto han sido convertidas a minúsculas.

,reseña,calificación,tipo_lugar,fuente,nombre,fecha,grupo_de_viaje
0,we just did the hot springs and slides for the...,5.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,06/07/2026 00:48:58,friends
1,i read a lot of negative reviews a few days be...,5.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,06/04/2026 17:40:19,family
2,this resort was amazing. we had two different ...,5.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,06/03/2026 16:45:40,family

In [13]:
# Dividimos por el espacio y nos quedamos con la primera parte (la fecha)
df['fecha'] = df['fecha'].str.split(' ').str[0]

print("✅ Fechas limpiadas. Ejemplos:")
df[['fecha']].head(10)

✅ Fechas limpiadas. Ejemplos:

        fecha
0  06/07/2026
1  06/04/2026
2  06/03/2026
3  06/03/2026
4  06/03/2026
5  05/31/2026
6  05/31/2026
7  05/31/2026
8  05/31/2026
9  05/31/2026

In [14]:
# Condición: reseña es nula, vacía o contiene solo espacios
condicion_vacia = df['reseña'].isna() | (df['reseña'].str.strip() == '')

total_vacias = condicion_vacia.sum()
print(f"Total de reseñas vacías: {total_vacias}")

if total_vacias > 0:
    # Mostrar algunos ejemplos de las filas que se eliminarán (si hay)
    print("\nPrimeras 5 filas con reseña vacía:")
    display(df[condicion_vacia].head(5))

    # Eliminar esas filas
    df = df[~condicion_vacia].copy()

    print(f"\n✅ Filas eliminadas. Nuevo tamaño del dataset: {df.shape}")
else:
    print("No se encontraron reseñas vacías.")

Total de reseñas vacías: 916

Primeras 5 filas con reseña vacía:

,reseña,calificación,tipo_lugar,fuente,nombre,fecha,grupo_de_viaje
6,NaN,5.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,05/31/2026,couple
8,NaN,5.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,05/31/2026,NaN
9,NaN,4.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,05/31/2026,NaN
10,NaN,5.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,05/30/2026,NaN
12,NaN,5.0,hotel,https://search.google.com/local/reviews?placei...,baldi hot springs hotel resort & spa,05/26/2026,friends

✅ Filas eliminadas. Nuevo tamaño del dataset: (2484, 7)

In [15]:
# Solo si no está instalada (ejecutar una sola vez)
!pip install langdetect

Requirement already satisfied: langdetect in c:\users\ferna\anaconda3\lib\site-packages (1.0.9)
Requirement already satisfied: six in c:\users\ferna\anaconda3\lib\site-packages (from langdetect) (1.16.0)

In [16]:
from langdetect import detect, LangDetectException
import numpy as np

def detectar_espanol(texto):
    try:
        return detect(texto) == 'es'
    except LangDetectException:
        # Si falla (por texto muy corto, solo números, etc.), lo consideramos no español
        return False

# Aplicamos la detección a la columna 'reseña'
print("Detectando idiomas... (puede tardar unos segundos)")
es_espanol = df['reseña'].apply(detectar_espanol)

# Contar resultados
total_no_espanol = (~es_espanol).sum()
print(f"Reseñas que NO están en español: {total_no_espanol}")

if total_no_espanol > 0:
    print("\nEjemplos de reseñas eliminadas (primeras 5):")
    display(df[~es_espanol][['reseña']].head(5))

# Filtrar solo las que son español
df = df[es_espanol].copy()

print(f"\n✅ Reseñas en español conservadas. Nuevo tamaño: {df.shape}")

Detectando idiomas... (puede tardar unos segundos)
Reseñas que NO están en español: 1697

Ejemplos de reseñas eliminadas (primeras 5):

                                              reseña
0  we just did the hot springs and slides for the...
1  i read a lot of negative reviews a few days be...
2  this resort was amazing. we had two different ...
3  price is the major factor,  one drink here is ...
4                       great place.. it's wonderful

✅ Reseñas en español conservadas. Nuevo tamaño: (787, 7)

In [17]:
import re
def eliminar_emojis(texto):
    if not isinstance(texto, str):
        return ""
    # Elimina emojis y símbolos no latinos, conservando letras acentuadas, puntuación básica, espacios
    texto_limpio = re.sub(r'[^\w\s.,!?;:áéíóúüñÁÉÍÓÚÜÑ]', '', texto, flags=re.UNICODE)
    # Normalizar espacios múltiples
    texto_limpio = re.sub(r'\s+', ' ', texto_limpio).strip()
    return texto_limpio

In [18]:
import re

def limpiar_caracteres_especiales(texto):
    """
    Conserva solo:
      - Letras (incluyendo acentos, diéresis y ñ/Ñ)
      - Números (0-9)
      - Espacios
    Elimina todo lo demás: puntuación, símbolos, etc.
    """
    if not isinstance(texto, str):
        return ""

    # Mantiene solo letras (incluye tildes y ñ), números y espacios
    texto = re.sub(r'[^a-záéíóúüñA-ZÁÉÍÓÚÜÑ0-9\s]', '', texto, flags=re.UNICODE)

    # Normaliza espacios múltiples y recorta extremos
    texto = re.sub(r'\s+', ' ', texto).strip()

    return texto

# Aplicar la limpieza
df['reseña'] = df['reseña'].apply(limpiar_caracteres_especiales)

# Verificar si alguna reseña quedó vacía después de la limpieza
vacias_post_limpieza = (df['reseña'] == '') | df['reseña'].isna()
total_vacias_post = vacias_post_limpieza.sum()
print(f"Reseñas vacías después de la limpieza: {total_vacias_post}")

if total_vacias_post > 0:
    df = df[~vacias_post_limpieza].copy()
    print(f"✅ Filas eliminadas. Nuevo tamaño: {df.shape}")

# Mostrar ejemplos
print("\nEjemplos de reseñas completamente limpias:")
df[['reseña']].head(5)

Reseñas vacías después de la limpieza: 0

Ejemplos de reseñas completamente limpias:

                                               reseña
16  fue una pésima experiencia llegamos solo por u...
22  todo muy bonito realmente me quedo sin palabra...
23  una experiencia relajante e imperdible en cost...
24  buena experiencia nos habían recomendado en gr...
26  un gran lugar para hospedarse un pasasar un ra...

In [31]:
!pip install pyspellchecker

Requirement already satisfied: pyspellchecker in c:\users\ferna\anaconda3\lib\site-packages (0.9.0)

In [32]:
from spellchecker import SpellChecker
import pandas as pd

# Crear el corrector en español
spell = SpellChecker(language='es')

def contar_errores(texto):
    """Cuenta las palabras que no están en el diccionario."""
    if not isinstance(texto, str) or texto.strip() == '':
        return 0
    palabras = texto.split()
    # Palabras que el corrector considera erróneas
    desconocidas = spell.unknown(palabras)
    return len(desconocidas)

def palabras_erroneas(texto):
    """Devuelve una lista de las palabras probablemente mal escritas."""
    if not isinstance(texto, str) or texto.strip() == '':
        return []
    palabras = texto.split()
    desconocidas = spell.unknown(palabras)
    return list(desconocidas)

# Aplicar a cada reseña
print("Analizando errores (puede tardar unos segundos)...")
df['cantidad_errores'] = df['reseña'].apply(contar_errores)
df['palabras_erroneas'] = df['reseña'].apply(palabras_erroneas)

# Resumen estadístico
total_resenas = len(df)
resenas_con_errores = (df['cantidad_errores'] > 0).sum()
print(f"\nTotal de reseñas: {total_resenas}")
print(f"Reseñas con al menos un posible error: {resenas_con_errores} ({100*resenas_con_errores/total_resenas:.1f}%)")

# Mostrar algunas reseñas con más errores
top_erroneas = df.nlargest(10, 'cantidad_errores')[['reseña', 'cantidad_errores', 'palabras_erroneas']]
print("\n🔟 Las 10 reseñas con más posibles errores ortográficos:")
for i, row in top_erroneas.iterrows():
    print(f"\nReseña (errores: {row['cantidad_errores']}):")
    print(row['reseña'][:200] + ('...' if len(row['reseña']) > 200 else ''))
    print(f"Palabras dudosas: {row['palabras_erroneas'][:15]}...")

Analizando errores (puede tardar unos segundos)...

Total de reseñas: 787
Reseñas con al menos un posible error: 671 (85.3%)

🔟 Las 10 reseñas con más posibles errores ortográficos:

Reseña (errores: 118):
la experiencia en general estuvo bien y el hotel tiene varios puntos positivos que disfrutamos las piscinas son muy bonitas amplias y agradables para pasar el día uno de los aspectos que más nos gustó...
Palabras dudosas: ['pasó', 'mejores', 'cambiarlas', 'atendernos', 'baños', 'bonitas', 'disfrutamos', 'deberían', 'audífonos', 'cambiarnos', 'piscinas', 'ensaladas', 'amables', 'detalles', 'reponiendo']...

Reseña (errores: 93):
ubicado en una de esas zonas modernas y vidriadas que podrían ser puerto madero en buenos aires o cualquier barrio cosmopolita de una gran ciudad si uno se despertara allí sin contexto podría creer qu...
Palabras dudosas: ['despertara', 'resueltos', 'concesiones', 'aceptó', 'parece', 'vidriadas', 'dónde', 'eligió', 'mesas', 'pies', 'modernas', 'abraza', 'show', 'cae', 'funciona']...

Reseña (errores: 77):
lamento decir que para mi y mi pareja fu una mala experiencia gastronomica empezando desde la llegada nos recibi una chica con lentesnosotros no teniamos reservaella fu a verificar que hubiera una mes...
Palabras dudosas: ['libres', 'carpaccio', 'experienciaseguros', 'llev', 'llegamos', 'vuelva', 'buenovegetales', 'tragos', 'mejorpero', 'discriminatorio', 'otras', 'quieriamos', 'barracuando', 'empezando', 'habian']...

Reseña (errores: 70):
estancia de 7 días con familia desde nuestra llegada nos encontramos con algunos inconvenientes que afectaron la experiencia que esperábamos al entrar a nuestra habitación notamos que las sábanas esta...
Palabras dudosas: ['serviciopor', 'supervisión', 'tablas', 'tuvimos', 'esperábamos', 'sufrimos', 'resultó', 'ofrecen', 'atendidos', 'puntos', 'aclararlo', 'afectaron', 'estaban', 'lácteos', 'amenidades']...

Reseña (errores: 64):
estuvimos hospedados 3 noches en el hotel en una habitación junior suite desde el día 11 hasta el sábado 14 de marzo de 2026 he ido en 4 ocasiones en los últimos años el hotel como desde la primera ve...
Palabras dudosas: ['años', 'invierten', 'out', 'urinarios', 'estuvimos', 'tiene', 'baños', 'dice', 'pague', 'ganas', 'dejadísimos', 'valen', 'reírse', 'masculinos', 'desayunar']...

Reseña (errores: 64):
un lugar espectacular y sin duda una visita obligada para cualquiera que viaje a manuel antonio el parque está muy bien mantenido los senderos principales son cómodos de recorrer y todo se encuentra e...
Palabras dudosas: ['guías', 'playas', 'antonio', 'tuvimos', 'quienes', 'condiciones', 'unos', 'mejores', 'mantenido', 'estuvimos', 'ocurre', 'oficiales', 'detenerse', 'puede', 'opciones']...

Reseña (errores: 54):
le he dado 2 oportunidades pensando que tal vez fue mala suerte o un mal día pero definitivamente no veo el valor de su menú la primera vez que fui hace un tiempo pedí un pescado al vapor en hoja de p...
Palabras dudosas: ['sabía', 'opacaba', 'extranjeros', 'hace', 'mini', 'llegó', 'turistas', 'restaurantes', 'marketing', 'camarones', 'esperando', 'menú', 'achiotada', 'tartar', 'oportunidades']...

Reseña (errores: 51):
es un lugar muy bonito las piscinas son amplias así que no estás tan cerca de otras personas la comida estuvo bien no deliciosa pero bien quise almorzar y cenar pero solamente había espacio para el al...
Palabras dudosas: ['qué', 'mandan', 'dejen', 'quise', 'contaminante', 'recomiendo', 'ví', 'cómo', 'especies', 'visito', 'ornamentales', 'sé', 'amplias', 'estuvo', 'deberían']...

Reseña (errores: 49):
al parecer es uno de los parques nacionales menos visitados y menos atractivos para los que le gusta la aventura extrema senderos cortos y sin pendientes son de nivel muy principiante el lugar es idea...
Palabras dudosas: ['demorado', 'debes', 'dice', 'atractivos', 'recomiendo', 'creo', 'ultimo', 'dijo', 'avistamiento', 'tuve', 'visitados', 'parques', 'youtube', 'niños', 'super']...

Reseña (errores: 48):
secrets papagayo costa rica es un lugar verdaderamente especial su mayor encanto está en su entorno una playa tranquila rodeada de montañas vegetación exuberante y fauna local que te hace sentir compl...
Palabras dudosas: ['cuartos', 'memorables', 'vive', 'actividades', 'buffet', 'hace', 'desconectado', 'pensados', 'cuidando', 'puedes', 'ganas', 'opciones', 'diferentes', 'adriana', 'aún']...

Los errores más comunes que cometen las personas a la hora de dejar su reseña en el sitio de google maps son:
1. Escribir las palabras pegadas haciendo que no tenga sentido el texto sin la debida separación
2. Tener bastantes errores ortográficos (confundiendo u omitiendo letras)
3. Repitiendo las mismas palabras una al lado de la otra

In [33]:
# Eliminar las columnas agregadas por el análisis de ortografía
columnas_a_eliminar = ['cantidad_errores', 'palabras_erroneas']

# Solo eliminamos las que realmente existen para evitar errores
df.drop(columns=[col for col in columnas_a_eliminar if col in df.columns], inplace=True)

print("✅ Columnas eliminadas. Columnas actuales:")
print(df.columns.tolist())

✅ Columnas eliminadas. Columnas actuales:
['reseña', 'calificación', 'tipo_lugar', 'fuente', 'nombre', 'fecha', 'grupo_de_viaje']

In [19]:
# Convertir calificación a entero (maneja valores nulos)
df['calificación'] = pd.to_numeric(df['calificación'], errors='coerce').astype('Int64')

# Verificar los valores únicos y sus tipos
print("Valores únicos en calificación:")
print(df['calificación'].unique())
print(f"\nTipo de dato: {df['calificación'].dtype}")

# Mostrar algunos ejemplos
df[['calificación']].head(10)

Valores únicos en calificación:
<IntegerArray>
[1, 5, 4, 3, 2]
Length: 5, dtype: Int64

Tipo de dato: Int64

    calificación
16             1
22             5
23             5
24             4
26             5
41             5
42             5
50             1
51             5
55             5

In [20]:
# Mostrar todos los valores únicos y su frecuencia
print("Valores únicos en 'grupo_de_viaje' y su cantidad:")
print(df['grupo_de_viaje'].value_counts(dropna=False))

Valores únicos en 'grupo_de_viaje' y su cantidad:
grupo_de_viaje
NaN        676
family      44
couple      33
friends     23
solo        11
Name: count, dtype: int64

In [21]:
# Diccionario de traducción
mapeo_grupo = {
    'family': 'familia',
    'couple': 'pareja',
    'friends': 'amigos'
    # 'solo' se queda igual, NaN no se toca
}

# Reemplazar solo los valores que están en el diccionario
df['grupo_de_viaje'] = df['grupo_de_viaje'].replace(mapeo_grupo)

print("✅ Valores actualizados. Conteo final:")
print(df['grupo_de_viaje'].value_counts(dropna=False))

✅ Valores actualizados. Conteo final:
grupo_de_viaje
NaN        676
familia     44
pareja      33
amigos      23
solo        11
Name: count, dtype: int64

In [22]:
# Guardar el DataFrame actual como CSV en data/processed/
ruta_salida = proyecto / 'data' / 'processed' / 'resenas_clean.csv'
ruta_salida.parent.mkdir(parents=True, exist_ok=True)  # crea la carpeta si no existe
df.to_csv(ruta_salida, index=False)

print(f"✅ Dataset limpio guardado en: {ruta_salida}")
print(f"Dimensiones: {df.shape}")

✅ Dataset limpio guardado en: C:\Reseñas_turisticas_CR\Rese-as-turisticas\data\processed\resenas_clean.csv
Dimensiones: (787, 7)

In [30]:
import os

ruta_descarga = os.path.join(os.path.expanduser("~"), "Downloads", "resenas_clean.csv")
df.to_csv(ruta_descarga, index=False)

print(f"✅ Archivo guardado en: {ruta_descarga}")

✅ Archivo guardado en: C:\Users\ferna\Downloads\resenas_clean.csv